// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReminNote.Infrastructure.Persistence;

#nullable disable

namespace ReminNote.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReminNoteDbContext))]
    [Migration("20260902141656_P3ReminderPersistence")]
    partial class P3ReminderPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.AppSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkdayBoundaryMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workday_boundary_minutes");

                    b.HasKey("Id")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_settings_singleton_id", "id = 1");

                            t.HasCheckConstraint("ck_app_settings_workday_boundary", "workday_boundary_minutes >= 0 AND workday_boundary_minutes <= 1439");
                        });
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.P25.P25ChangeJournalEntity", b =>
                {
                    b.Property<string>("ProfileScope")
                        .HasMaxLength(67)
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_scope");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<long>("ChangeOrdinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("change_ordinal");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT")
                        .HasColumnName("batch_id");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("change_kind");

                    b.Property<string>("ChangedAtUtc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_at_utc");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.HasKey("ProfileScope", "Revision", "ChangeOrdinal")
                        .HasName("pk_change_journal");

                    b.HasIndex("ProfileScope", "Revision", "ChangeOrdinal")
                        .HasDatabaseName("ix_change_journal_profile_revision");

                    b.ToTable("change_journal", null, t =>
                        {
                            t.HasCheckConstraint("ck_change_journal_batch_id", "length(batch_id) BETWEEN 1 AND 96");

                            t.HasCheckConstraint("ck_change_journal_change_kind", "length(change_kind) BETWEEN 1 AND 64");

                            t.HasCheckConstraint("ck_change_journal_changed_at", "length(changed_at_utc) BETWEEN 1 AND 64");

                            t.HasCheckConstraint("ck_change_journal_entity_id", "length(entity_id) BETWEEN 1 AND 256");

                            t.HasCheckConstraint("ck_change_journal_entity_type", "length(entity_type) BETWEEN 1 AND 128");

                            t.HasCheckConstraint("ck_change_journal_ordinal", "change_ordinal >= 0");

                            t.HasCheckConstraint("ck_change_journal_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.P25.P25CommandReceiptEntity", b =>
                {
                    b.Property<string>("ActualUserSid")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("actual_user_sid");

                    b.Property<string>("ProfileScope")
                        .HasMaxLength(67)
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_scope");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("AgentInstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_instance_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<byte[]>("CanonicalPayloadHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("canonical_payload_hash");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("changed");

                    b.Property<long?>("CommittedRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("committed_revision");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("FirstAcceptedAtUtc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_accepted_at_utc");

                    b.Property<string>("FirstRequestId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_request_id");

                    b.Property<string>("HashVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("hash_version");

                    b.Property<string>("LastRequestId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_request_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ActualUserSid", "ProfileScope", "IdempotencyKey")
                        .HasName("pk_command_receipt");

                    b.HasIndex("ProfileScope", "IdempotencyKey")
                        .HasDatabaseName("ix_command_receipt_profile_key");

                    b.ToTable("command_receipt", null, t =>
                        {
                            t.HasCheckConstraint("ck_command_receipt_agent_instance_id", "agent_instance_id IS NULL OR length(agent_instance_id) = 36");

                            t.HasCheckConstraint("ck_command_receipt_attempt_count", "attempt_count BETWEEN 1 AND 2");

                            t.HasCheckConstraint("ck_command_receipt_changed", "changed IN (0, 1)");

                            t.HasCheckConstraint("ck_command_receipt_committed_revision", "committed_revision IS NULL OR committed_revision >= 0");

                            t.HasCheckConstraint("ck_command_receipt_error_code", "error_code IS NULL OR length(error_code) BETWEEN 1 AND 160");

                            t.HasCheckConstraint("ck_command_receipt_first_accepted", "length(first_accepted_at_utc) BETWEEN 1 AND 64");

                            t.HasCheckConstraint("ck_command_receipt_first_request_id", "length(first_request_id) = 36");

                            t.HasCheckConstraint("ck_command_receipt_hash", "length(canonical_payload_hash) = 32");

                            t.HasCheckConstraint("ck_command_receipt_hash_version", "length(hash_version) BETWEEN 1 AND 32");

                            t.HasCheckConstraint("ck_command_receipt_idempotency_key", "length(idempotency_key) = 36");

                            t.HasCheckConstraint("ck_command_receipt_last_request_id", "length(last_request_id) = 36");

                            t.HasCheckConstraint("ck_command_receipt_operation", "length(operation) BETWEEN 1 AND 96");

                            t.HasCheckConstraint("ck_command_receipt_sid", "length(actual_user_sid) BETWEEN 1 AND 256");

                            t.HasCheckConstraint("ck_command_receipt_status", "status IN ('PENDING','COMMITTED','REJECTED_STALE','REJECTED','ROLLED_BACK','CANCELLED','TIMED_OUT','UNKNOWN')");

                            t.HasCheckConstraint("ck_command_receipt_updated", "length(updated_at_utc) BETWEEN 1 AND 64");
                        });
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.P25.P25RevisionStateEntity", b =>
                {
                    b.Property<string>("ProfileScope")
                        .HasMaxLength(67)
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_scope");

                    b.Property<long>("CurrentRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_revision");

                    b.Property<long>("OldestAvailableRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("oldest_available_revision");

                    b.HasKey("ProfileScope")
                        .HasName("pk_revision_state");

                    b.ToTable("revision_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_revision_state_current_revision", "current_revision >= 0");

                            t.HasCheckConstraint("ck_revision_state_oldest_revision", "oldest_available_revision >= 0");

                            t.HasCheckConstraint("ck_revision_state_revision_order", "oldest_available_revision = 0 OR oldest_available_revision <= current_revision");
                        });
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.Reminders.ReminderDeliveryAttemptEntity", b =>
                {
                    b.Property<string>("AttemptId")
                        .HasColumnType("TEXT")
                        .HasColumnName("attempt_id");

                    b.Property<string>("AttemptedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("attempted_at_utc");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.HasKey("AttemptId")
                        .HasName("pk_reminder_delivery_attempts");

                    b.HasIndex("InstanceId", "AttemptedAtUtc")
                        .HasDatabaseName("ix_reminder_delivery_attempts_instance_time");

                    b.HasIndex("InstanceId", "Channel")
                        .HasDatabaseName("ix_reminder_delivery_attempts_instance_channel");

                    b.ToTable("reminder_delivery_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminder_delivery_attempts_channel", "channel IN ('TOAST','TRAY','WIDGET','SOUND','WAKE_TIMER')");

                            t.HasCheckConstraint("ck_reminder_delivery_attempts_error_code", "error_code IS NULL OR length(trim(error_code)) BETWEEN 1 AND 160");

                            t.HasCheckConstraint("ck_reminder_delivery_attempts_id_uuid_v7", "attempt_id IS NOT NULL AND length(attempt_id) = 36 AND attempt_id = lower(attempt_id) AND attempt_id NOT GLOB '*[^0-9a-f-]*' AND substr(attempt_id, 9, 1) = '-' AND substr(attempt_id, 14, 1) = '-' AND substr(attempt_id, 19, 1) = '-' AND substr(attempt_id, 24, 1) = '-' AND lower(substr(attempt_id, 15, 1)) = '7' AND lower(substr(attempt_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_delivery_attempts_instance_id_uuid_v7", "instance_id IS NOT NULL AND length(instance_id) = 36 AND instance_id = lower(instance_id) AND instance_id NOT GLOB '*[^0-9a-f-]*' AND substr(instance_id, 9, 1) = '-' AND substr(instance_id, 14, 1) = '-' AND substr(instance_id, 19, 1) = '-' AND substr(instance_id, 24, 1) = '-' AND lower(substr(instance_id, 15, 1)) = '7' AND lower(substr(instance_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_delivery_attempts_outcome", "outcome IN ('DELIVERED','BLOCKED','UNAVAILABLE','FAILED','SUPPRESSED_QUIET_HOURS','NOT_ATTEMPTED')");

                            t.HasCheckConstraint("ck_reminder_delivery_attempts_timestamp_format", "length(attempted_at_utc) = 30");
                        });
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.Reminders.ReminderInstanceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AttemptOrdinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_ordinal");

                    b.Property<string>("Lifecycle")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lifecycle");

                    b.Property<string>("LogicalReminderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("logical_reminder_id");

                    b.Property<string>("OccurrenceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurrence_id");

                    b.Property<int>("PinnedSnapshot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pinned_snapshot");

                    b.Property<string>("PrioritySnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("priority_snapshot");

                    b.Property<string>("PurposeSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("purpose_snapshot");

                    b.Property<string>("ReadAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("read_at_utc");

                    b.Property<string>("ResolutionAction")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution_action");

                    b.Property<string>("ResolvedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at_utc");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_id");

                    b.Property<string>("ScheduleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.Property<string>("TriggeredAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("triggered_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_reminder_instances");

                    b.HasIndex("RuleId");

                    b.HasIndex("ScheduleId")
                        .IsUnique()
                        .HasDatabaseName("ux_reminder_instances_schedule_id");

                    b.HasIndex("LogicalReminderId", "AttemptOrdinal")
                        .IsUnique()
                        .HasDatabaseName("ux_reminder_instances_logical_attempt");

                    b.HasIndex("LogicalReminderId", "TriggeredAtUtc")
                        .HasDatabaseName("ix_reminder_instances_logical_triggered_at");

                    b.HasIndex("OccurrenceId", "Lifecycle")
                        .HasDatabaseName("ix_reminder_instances_occurrence_lifecycle");

                    b.ToTable("reminder_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminder_instances_attempt_ordinal", "attempt_ordinal >= 1");

                            t.HasCheckConstraint("ck_reminder_instances_id_uuid_v7", "id IS NOT NULL AND length(id) = 36 AND id = lower(id) AND id NOT GLOB '*[^0-9a-f-]*' AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-' AND lower(substr(id, 15, 1)) = '7' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_instances_lifecycle", "lifecycle IN ('UNREAD','READ','RESOLVED')");

                            t.HasCheckConstraint("ck_reminder_instances_lifecycle_shape", "(lifecycle = 'UNREAD' AND read_at_utc IS NULL AND resolved_at_utc IS NULL AND resolution_action IS NULL) OR (lifecycle = 'READ' AND read_at_utc IS NOT NULL AND resolved_at_utc IS NULL AND resolution_action IS NULL) OR (lifecycle = 'RESOLVED' AND read_at_utc IS NOT NULL AND resolved_at_utc IS NOT NULL AND resolution_action IS NOT NULL)");

                            t.HasCheckConstraint("ck_reminder_instances_logical_id_uuid_v7", "logical_reminder_id IS NOT NULL AND length(logical_reminder_id) = 36 AND logical_reminder_id = lower(logical_reminder_id) AND logical_reminder_id NOT GLOB '*[^0-9a-f-]*' AND substr(logical_reminder_id, 9, 1) = '-' AND substr(logical_reminder_id, 14, 1) = '-' AND substr(logical_reminder_id, 19, 1) = '-' AND substr(logical_reminder_id, 24, 1) = '-' AND lower(substr(logical_reminder_id, 15, 1)) = '7' AND lower(substr(logical_reminder_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_instances_occurrence_id_uuid_v7", "occurrence_id IS NOT NULL AND length(occurrence_id) = 36 AND occurrence_id = lower(occurrence_id) AND occurrence_id NOT GLOB '*[^0-9a-f-]*' AND substr(occurrence_id, 9, 1) = '-' AND substr(occurrence_id, 14, 1) = '-' AND substr(occurrence_id, 19, 1) = '-' AND substr(occurrence_id, 24, 1) = '-' AND lower(substr(occurrence_id, 15, 1)) = '7' AND lower(substr(occurrence_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_instances_pinned_snapshot", "pinned_snapshot IN (0,1)");

                            t.HasCheckConstraint("ck_reminder_instances_priority_snapshot", "priority_snapshot IN ('LOW','NORMAL','HIGH')");

                            t.HasCheckConstraint("ck_reminder_instances_purpose_snapshot", "purpose_snapshot IN ('TASK_PRE_START','TASK_START','TASK_RANGE_END','TASK_CUSTOM')");

                            t.HasCheckConstraint("ck_reminder_instances_resolution_action", "resolution_action IS NULL OR resolution_action IN ('DONE','SNOOZE','WATCHED','WATCH_LATER','SKIP','IGNORE')");

                            t.HasCheckConstraint("ck_reminder_instances_rule_id_uuid_v7", "rule_id IS NOT NULL AND length(rule_id) = 36 AND rule_id = lower(rule_id) AND rule_id NOT GLOB '*[^0-9a-f-]*' AND substr(rule_id, 9, 1) = '-' AND substr(rule_id, 14, 1) = '-' AND substr(rule_id, 19, 1) = '-' AND substr(rule_id, 24, 1) = '-' AND lower(substr(rule_id, 15, 1)) = '7' AND lower(substr(rule_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_instances_schedule_id_uuid_v7", "schedule_id IS NOT NULL AND length(schedule_id) = 36 AND schedule_id = lower(schedule_id) AND schedule_id NOT GLOB '*[^0-9a-f-]*' AND substr(schedule_id, 9, 1) = '-' AND substr(schedule_id, 14, 1) = '-' AND substr(schedule_id, 19, 1) = '-' AND substr(schedule_id, 24, 1) = '-' AND lower(substr(schedule_id, 15, 1)) = '7' AND lower(substr(schedule_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_instances_timestamp_order", "(read_at_utc IS NULL OR read_at_utc >= triggered_at_utc) AND (resolved_at_utc IS NULL OR (read_at_utc IS NOT NULL AND resolved_at_utc >= read_at_utc))");

                            t.HasCheckConstraint("ck_reminder_instances_timestamps_format", "length(triggered_at_utc) = 30 AND read_at_utc IS NULL OR length(read_at_utc) = 30 AND resolved_at_utc IS NULL OR length(resolved_at_utc) = 30");
                        });
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.Reminders.ReminderRuleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AbsoluteAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("absolute_at_utc");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("OccurrenceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurrence_id");

                    b.Property<long?>("OffsetSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("offset_seconds");

                    b.Property<int>("Pinned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pinned");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("priority");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("purpose");

                    b.Property<int>("RepeatEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repeat_enabled");

                    b.Property<long?>("RepeatIntervalSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repeat_interval_seconds");

                    b.Property<int?>("RepeatMaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repeat_max_count");

                    b.Property<long>("RuleRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("rule_revision");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_kind");

                    b.Property<string>("TimingAnchor")
                        .HasColumnType("TEXT")
                        .HasColumnName("timing_anchor");

                    b.Property<string>("TimingKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timing_kind");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WakePolicy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("wake_policy");

                    b.HasKey("Id")
                        .HasName("pk_reminder_rules");

                    b.HasIndex("OccurrenceId", "Enabled")
                        .HasDatabaseName("ix_reminder_rules_occurrence_enabled");

                    b.HasIndex("TargetKind", "TargetId", "OccurrenceId")
                        .HasDatabaseName("ix_reminder_rules_target_occurrence");

                    b.ToTable("reminder_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminder_rules_id_uuid_v7", "id IS NOT NULL AND length(id) = 36 AND id = lower(id) AND id NOT GLOB '*[^0-9a-f-]*' AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-' AND lower(substr(id, 15, 1)) = '7' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_rules_occurrence_id_uuid_v7", "occurrence_id IS NOT NULL AND length(occurrence_id) = 36 AND occurrence_id = lower(occurrence_id) AND occurrence_id NOT GLOB '*[^0-9a-f-]*' AND substr(occurrence_id, 9, 1) = '-' AND substr(occurrence_id, 14, 1) = '-' AND substr(occurrence_id, 19, 1) = '-' AND substr(occurrence_id, 24, 1) = '-' AND lower(substr(occurrence_id, 15, 1)) = '7' AND lower(substr(occurrence_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_rules_priority", "priority IN ('LOW','NORMAL','HIGH')");

                            t.HasCheckConstraint("ck_reminder_rules_purpose", "purpose IN ('TASK_PRE_START','TASK_START','TASK_RANGE_END','TASK_CUSTOM')");

                            t.HasCheckConstraint("ck_reminder_rules_purpose_timing", "(purpose = 'TASK_CUSTOM' AND timing_kind = 'ABSOLUTE_UTC') OR (purpose = 'TASK_RANGE_END' AND timing_kind = 'RELATIVE' AND timing_anchor = 'RANGE_END') OR (purpose = 'TASK_START' AND timing_kind = 'RELATIVE' AND timing_anchor IN ('TASK_TIME','RANGE_START')) OR (purpose = 'TASK_PRE_START' AND timing_kind = 'RELATIVE' AND timing_anchor IN ('TASK_TIME','RANGE_START') AND offset_seconds < 0)");

                            t.HasCheckConstraint("ck_reminder_rules_repeat_enabled", "repeat_enabled IN (0,1) AND pinned IN (0,1) AND enabled IN (0,1)");

                            t.HasCheckConstraint("ck_reminder_rules_repeat_values", "(repeat_interval_seconds IS NULL OR repeat_interval_seconds > 0) AND (repeat_max_count IS NULL OR repeat_max_count > 0) AND (repeat_enabled = 0 OR repeat_interval_seconds IS NOT NULL)");

                            t.HasCheckConstraint("ck_reminder_rules_revision", "rule_revision >= 1");

                            t.HasCheckConstraint("ck_reminder_rules_target_id_uuid_v7", "target_id IS NOT NULL AND length(target_id) = 36 AND target_id = lower(target_id) AND target_id NOT GLOB '*[^0-9a-f-]*' AND substr(target_id, 9, 1) = '-' AND substr(target_id, 14, 1) = '-' AND substr(target_id, 19, 1) = '-' AND substr(target_id, 24, 1) = '-' AND lower(substr(target_id, 15, 1)) = '7' AND lower(substr(target_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_rules_target_kind", "target_kind IN ('TASK_INSTANCE')");

                            t.HasCheckConstraint("ck_reminder_rules_timestamp_order", "updated_at_utc >= created_at_utc");

                            t.HasCheckConstraint("ck_reminder_rules_timestamps_format", "length(created_at_utc) = 30 AND length(updated_at_utc) = 30 AND absolute_at_utc IS NULL OR length(absolute_at_utc) = 30");

                            t.HasCheckConstraint("ck_reminder_rules_timing_kind", "timing_kind IN ('RELATIVE','ABSOLUTE_UTC')");

                            t.HasCheckConstraint("ck_reminder_rules_timing_shape", "(timing_kind = 'RELATIVE' AND timing_anchor IN ('TASK_TIME','RANGE_START','RANGE_END') AND offset_seconds IS NOT NULL AND absolute_at_utc IS NULL) OR (timing_kind = 'ABSOLUTE_UTC' AND timing_anchor IS NULL AND offset_seconds IS NULL AND absolute_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_reminder_rules_wake_policy", "wake_policy IN ('DEFAULT','YES','NO')");
                        });
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.Reminders.ReminderScheduleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cause");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LogicalReminderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("logical_reminder_id");

                    b.Property<string>("OccurrenceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurrence_id");

                    b.Property<string>("OriginScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("origin_schedule_id");

                    b.Property<int>("PinnedSnapshot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pinned_snapshot");

                    b.Property<string>("PrioritySnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("priority_snapshot");

                    b.Property<string>("PurposeSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("purpose_snapshot");

                    b.Property<string>("ReplacementScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("replacement_schedule_id");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_id");

                    b.Property<long>("RuleRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rule_revision");

                    b.Property<long>("ScheduleRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_revision");

                    b.Property<string>("State")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("TerminalAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_at_utc");

                    b.Property<string>("TerminalReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_reason");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("TriggerAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_reminder_schedules");

                    b.HasIndex("OriginScheduleId");

                    b.HasIndex("ReplacementScheduleId");

                    b.HasIndex("LogicalReminderId", "ScheduleRevision")
                        .HasDatabaseName("ix_reminder_schedules_logical_revision");

                    b.HasIndex("OccurrenceId", "State")
                        .HasDatabaseName("ix_reminder_schedules_occurrence_state");

                    b.HasIndex("State", "TriggerAtUtc")
                        .HasDatabaseName("ix_reminder_schedules_state_trigger_at_utc");

                    b.HasIndex("RuleId", "OccurrenceId", "ScheduleRevision")
                        .IsUnique()
                        .HasDatabaseName("ux_reminder_schedules_rule_occurrence_revision");

                    b.ToTable("reminder_schedules", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminder_schedules_cause", "cause IN ('RULE','SNOOZE','REPEAT')");

                            t.HasCheckConstraint("ck_reminder_schedules_id_uuid_v7", "id IS NOT NULL AND length(id) = 36 AND id = lower(id) AND id NOT GLOB '*[^0-9a-f-]*' AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-' AND lower(substr(id, 15, 1)) = '7' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_schedules_logical_id_uuid_v7", "logical_reminder_id IS NOT NULL AND length(logical_reminder_id) = 36 AND logical_reminder_id = lower(logical_reminder_id) AND logical_reminder_id NOT GLOB '*[^0-9a-f-]*' AND substr(logical_reminder_id, 9, 1) = '-' AND substr(logical_reminder_id, 14, 1) = '-' AND substr(logical_reminder_id, 19, 1) = '-' AND substr(logical_reminder_id, 24, 1) = '-' AND lower(substr(logical_reminder_id, 15, 1)) = '7' AND lower(substr(logical_reminder_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_schedules_occurrence_id_uuid_v7", "occurrence_id IS NOT NULL AND length(occurrence_id) = 36 AND occurrence_id = lower(occurrence_id) AND occurrence_id NOT GLOB '*[^0-9a-f-]*' AND substr(occurrence_id, 9, 1) = '-' AND substr(occurrence_id, 14, 1) = '-' AND substr(occurrence_id, 19, 1) = '-' AND substr(occurrence_id, 24, 1) = '-' AND lower(substr(occurrence_id, 15, 1)) = '7' AND lower(substr(occurrence_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_schedules_origin_id_uuid_v7", "origin_schedule_id IS NULL OR (origin_schedule_id IS NOT NULL AND length(origin_schedule_id) = 36 AND origin_schedule_id = lower(origin_schedule_id) AND origin_schedule_id NOT GLOB '*[^0-9a-f-]*' AND substr(origin_schedule_id, 9, 1) = '-' AND substr(origin_schedule_id, 14, 1) = '-' AND substr(origin_schedule_id, 19, 1) = '-' AND substr(origin_schedule_id, 24, 1) = '-' AND lower(substr(origin_schedule_id, 15, 1)) = '7' AND lower(substr(origin_schedule_id, 20, 1)) IN ('8', '9', 'a', 'b'))");

                            t.HasCheckConstraint("ck_reminder_schedules_origin_shape", "(cause = 'RULE' AND origin_schedule_id IS NULL) OR (cause IN ('SNOOZE','REPEAT') AND origin_schedule_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_reminder_schedules_pinned_snapshot", "pinned_snapshot IN (0,1)");

                            t.HasCheckConstraint("ck_reminder_schedules_priority_snapshot", "priority_snapshot IN ('LOW','NORMAL','HIGH')");

                            t.HasCheckConstraint("ck_reminder_schedules_purpose_snapshot", "purpose_snapshot IN ('TASK_PRE_START','TASK_START','TASK_RANGE_END','TASK_CUSTOM')");

                            t.HasCheckConstraint("ck_reminder_schedules_reason", "terminal_reason IS NULL OR terminal_reason IN ('DUE_CONSUMED','RULE_REBUILT','TASK_PLAN_CHANGED','TIME_ZONE_CHANGED','TASK_RESULT_RECORDED','RULE_DISABLED','TASK_DELETED','RECOVERY_OBSOLETE','MANUAL_CANCELLED','REPLACED')");

                            t.HasCheckConstraint("ck_reminder_schedules_replacement_id_uuid_v7", "replacement_schedule_id IS NULL OR (replacement_schedule_id IS NOT NULL AND length(replacement_schedule_id) = 36 AND replacement_schedule_id = lower(replacement_schedule_id) AND replacement_schedule_id NOT GLOB '*[^0-9a-f-]*' AND substr(replacement_schedule_id, 9, 1) = '-' AND substr(replacement_schedule_id, 14, 1) = '-' AND substr(replacement_schedule_id, 19, 1) = '-' AND substr(replacement_schedule_id, 24, 1) = '-' AND lower(substr(replacement_schedule_id, 15, 1)) = '7' AND lower(substr(replacement_schedule_id, 20, 1)) IN ('8', '9', 'a', 'b'))");

                            t.HasCheckConstraint("ck_reminder_schedules_replacement_not_self", "replacement_schedule_id IS NULL OR replacement_schedule_id <> id");

                            t.HasCheckConstraint("ck_reminder_schedules_revision", "rule_revision >= 1 AND schedule_revision >= 1");

                            t.HasCheckConstraint("ck_reminder_schedules_rule_id_uuid_v7", "rule_id IS NOT NULL AND length(rule_id) = 36 AND rule_id = lower(rule_id) AND rule_id NOT GLOB '*[^0-9a-f-]*' AND substr(rule_id, 9, 1) = '-' AND substr(rule_id, 14, 1) = '-' AND substr(rule_id, 19, 1) = '-' AND substr(rule_id, 24, 1) = '-' AND lower(substr(rule_id, 15, 1)) = '7' AND lower(substr(rule_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_reminder_schedules_state", "state IN ('PENDING','CONSUMED','SUPERSEDED','CANCELLED','EXPIRED')");

                            t.HasCheckConstraint("ck_reminder_schedules_state_shape", "(state = 'PENDING' AND terminal_reason IS NULL AND replacement_schedule_id IS NULL AND terminal_at_utc IS NULL) OR (state = 'CONSUMED' AND terminal_reason = 'DUE_CONSUMED' AND replacement_schedule_id IS NULL AND terminal_at_utc IS NOT NULL) OR (state = 'SUPERSEDED' AND terminal_reason IS NOT NULL AND replacement_schedule_id IS NOT NULL AND terminal_at_utc IS NOT NULL) OR (state IN ('CANCELLED','EXPIRED') AND terminal_reason IS NOT NULL AND replacement_schedule_id IS NULL AND terminal_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_reminder_schedules_timestamp_order", "terminal_at_utc IS NULL OR terminal_at_utc >= created_at_utc");

                            t.HasCheckConstraint("ck_reminder_schedules_timestamps_format", "length(trigger_at_utc) = 30 AND length(created_at_utc) = 30 AND terminal_at_utc IS NULL OR length(terminal_at_utc) = 30");

                            t.HasCheckConstraint("ck_reminder_schedules_timezone", "time_zone_id IS NULL OR length(trim(time_zone_id)) BETWEEN 1 AND 128");
                        });
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContinuedFromTaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("continued_from_task_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("LocalDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("local_date");

                    b.Property<long?>("RangeEnd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("range_end");

                    b.Property<long?>("RangeStart")
                        .HasColumnType("INTEGER")
                        .HasColumnName("range_start");

                    b.Property<int?>("Result")
                        .HasColumnType("INTEGER")
                        .HasColumnName("result");

                    b.Property<string>("ResultNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_note");

                    b.Property<string>("ResultRecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_recorded_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<long?>("TimePoint")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_point");

                    b.Property<int>("TimeType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("ContinuedFromTaskId")
                        .HasDatabaseName("ix_tasks_continued_from_task_id");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_continuation_not_self", "continued_from_task_id IS NULL OR continued_from_task_id <> id");

                            t.HasCheckConstraint("ck_tasks_id_uuid_v7", "length(id) = 36 AND id NOT GLOB '*[^0-9A-Fa-f-]*' AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-' AND lower(substr(id, 15, 1)) = '7' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_tasks_partial_requires_range", "result IS NULL OR result <> 2 OR time_type = 2");

                            t.HasCheckConstraint("ck_tasks_result_metadata", "(result IS NULL AND result_recorded_at IS NULL AND result_note IS NULL) OR (result IS NOT NULL AND result_recorded_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_tasks_result_timestamp_order", "result_recorded_at IS NULL OR (result_recorded_at >= created_at AND result_recorded_at <= updated_at)");

                            t.HasCheckConstraint("ck_tasks_result_value", "result IS NULL OR result IN (0, 1, 2)");

                            t.HasCheckConstraint("ck_tasks_sort_order_non_negative", "sort_order >= 0");

                            t.HasCheckConstraint("ck_tasks_time_shape", "(time_type = 0 AND time_point IS NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 1 AND time_point IS NOT NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 2 AND time_point IS NULL AND range_start IS NOT NULL AND range_end IS NOT NULL AND range_start <> range_end)");

                            t.HasCheckConstraint("ck_tasks_time_values", "(time_point IS NULL OR (time_point >= 0 AND time_point < 86400000000000)) AND (range_start IS NULL OR (range_start >= 0 AND range_start < 86400000000000)) AND (range_end IS NULL OR (range_end >= 0 AND range_end < 86400000000000))");

                            t.HasCheckConstraint("ck_tasks_timestamp_order", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_tasks_title_not_blank", "length(trim(title)) > 0");
                        });
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContinuedFromTaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("continued_from_task_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("LocalDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("local_date");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<long?>("RangeEnd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("range_end");

                    b.Property<long?>("RangeStart")
                        .HasColumnType("INTEGER")
                        .HasColumnName("range_start");

                    b.Property<string>("RelatedTaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("related_task_id");

                    b.Property<int?>("Result")
                        .HasColumnType("INTEGER")
                        .HasColumnName("result");

                    b.Property<string>("ResultNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_note");

                    b.Property<string>("ResultRecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_recorded_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<long?>("TimePoint")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_point");

                    b.Property<int>("TimeType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_task_history");

                    b.HasIndex("ContinuedFromTaskId")
                        .HasDatabaseName("ix_task_history_continued_from_task_id");

                    b.HasIndex("RelatedTaskId")
                        .HasDatabaseName("ix_task_history_related_task_id");

                    b.HasIndex("TaskId", "Id")
                        .HasDatabaseName("ix_task_history_task_id_id");

                    b.ToTable("task_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_history_continuation_metadata", "(kind <> 2 AND related_task_id IS NULL) OR (kind = 2 AND related_task_id IS NOT NULL AND continued_from_task_id = related_task_id AND task_id <> related_task_id)");

                            t.HasCheckConstraint("ck_task_history_id_uuid_v7", "length(task_id) = 36 AND task_id NOT GLOB '*[^0-9A-Fa-f-]*' AND substr(task_id, 9, 1) = '-' AND substr(task_id, 14, 1) = '-' AND substr(task_id, 19, 1) = '-' AND substr(task_id, 24, 1) = '-' AND lower(substr(task_id, 15, 1)) = '7' AND lower(substr(task_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_task_history_kind", "kind IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_task_history_partial_requires_range", "result IS NULL OR result <> 2 OR time_type = 2");

                            t.HasCheckConstraint("ck_task_history_result_metadata", "(result IS NULL AND result_recorded_at IS NULL AND result_note IS NULL) OR (result IS NOT NULL AND result_recorded_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_task_history_result_timestamp_order", "result_recorded_at IS NULL OR (result_recorded_at >= created_at AND result_recorded_at <= updated_at)");

                            t.HasCheckConstraint("ck_task_history_result_value", "result IS NULL OR result IN (0, 1, 2)");

                            t.HasCheckConstraint("ck_task_history_sort_order_non_negative", "sort_order >= 0");

                            t.HasCheckConstraint("ck_task_history_time_shape", "(time_type = 0 AND time_point IS NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 1 AND time_point IS NOT NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 2 AND time_point IS NULL AND range_start IS NOT NULL AND range_end IS NOT NULL AND range_start <> range_end)");

                            t.HasCheckConstraint("ck_task_history_time_values", "(time_point IS NULL OR (time_point >= 0 AND time_point < 86400000000000)) AND (range_start IS NULL OR (range_start >= 0 AND range_start < 86400000000000)) AND (range_end IS NULL OR (range_end >= 0 AND range_end < 86400000000000))");

                            t.HasCheckConstraint("ck_task_history_timestamp_order", "updated_at >= created_at AND occurred_at >= created_at");

                            t.HasCheckConstraint("ck_task_history_title_not_blank", "length(trim(title)) > 0");
                        });
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.P25.P25ChangeJournalEntity", b =>
                {
                    b.HasOne("ReminNote.Infrastructure.Persistence.P25.P25RevisionStateEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileScope")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.P25.P25CommandReceiptEntity", b =>
                {
                    b.HasOne("ReminNote.Infrastructure.Persistence.P25.P25RevisionStateEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileScope")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.Reminders.ReminderDeliveryAttemptEntity", b =>
                {
                    b.HasOne("ReminNote.Infrastructure.Persistence.Reminders.ReminderInstanceEntity", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.Reminders.ReminderInstanceEntity", b =>
                {
                    b.HasOne("ReminNote.Infrastructure.Persistence.Reminders.ReminderRuleEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReminNote.Infrastructure.Persistence.Reminders.ReminderScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.Reminders.ReminderScheduleEntity", b =>
                {
                    b.HasOne("ReminNote.Infrastructure.Persistence.Reminders.ReminderScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("OriginScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReminNote.Infrastructure.Persistence.Reminders.ReminderScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("ReplacementScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReminNote.Infrastructure.Persistence.Reminders.ReminderRuleEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskEntity", b =>
                {
                    b.HasOne("ReminNote.Infrastructure.Persistence.TaskEntity", null)
                        .WithMany()
                        .HasForeignKey("ContinuedFromTaskId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskHistoryEntity", b =>
                {
                    b.HasOne("ReminNote.Infrastructure.Persistence.TaskEntity", null)
                        .WithMany()
                        .HasForeignKey("ContinuedFromTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReminNote.Infrastructure.Persistence.TaskEntity", null)
                        .WithMany()
                        .HasForeignKey("RelatedTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReminNote.Infrastructure.Persistence.TaskEntity", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
