// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReminNote.Infrastructure.Persistence;

#nullable disable

namespace ReminNote.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReminNoteDbContext))]
    [Migration("20260828025922_InitialTaskSchema")]
    partial class InitialTaskSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("LocalDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("local_date");

                    b.Property<long?>("RangeEnd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("range_end");

                    b.Property<long?>("RangeStart")
                        .HasColumnType("INTEGER")
                        .HasColumnName("range_start");

                    b.Property<int?>("Result")
                        .HasColumnType("INTEGER")
                        .HasColumnName("result");

                    b.Property<string>("ResultNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_note");

                    b.Property<string>("ResultRecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_recorded_at");

                    b.Property<long?>("TimePoint")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_point");

                    b.Property<int>("TimeType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_id_uuid_v7", "length(id) = 36 AND id NOT GLOB '*[^0-9A-Fa-f-]*' AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-' AND lower(substr(id, 15, 1)) = '7' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_tasks_partial_requires_range", "result IS NULL OR result <> 2 OR time_type = 2");

                            t.HasCheckConstraint("ck_tasks_result_metadata", "(result IS NULL AND result_recorded_at IS NULL AND result_note IS NULL) OR (result IS NOT NULL AND result_recorded_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_tasks_result_timestamp_order", "result_recorded_at IS NULL OR (result_recorded_at >= created_at AND result_recorded_at <= updated_at)");

                            t.HasCheckConstraint("ck_tasks_result_value", "result IS NULL OR result IN (0, 1, 2)");

                            t.HasCheckConstraint("ck_tasks_time_shape", "(time_type = 0 AND time_point IS NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 1 AND time_point IS NOT NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 2 AND time_point IS NULL AND range_start IS NOT NULL AND range_end IS NOT NULL AND range_start <> range_end)");

                            t.HasCheckConstraint("ck_tasks_time_values", "(time_point IS NULL OR (time_point >= 0 AND time_point < 86400000000000)) AND (range_start IS NULL OR (range_start >= 0 AND range_start < 86400000000000)) AND (range_end IS NULL OR (range_end >= 0 AND range_end < 86400000000000))");

                            t.HasCheckConstraint("ck_tasks_timestamp_order", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_tasks_title_not_blank", "length(trim(title)) > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
