// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ReminNote.Infrastructure.Persistence;

#nullable disable

namespace ReminNote.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ReminNoteDbContext))]
partial class ReminNoteDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.AppSettingsEntity", b =>
        {
            b.Property<int>("Id")
                .HasColumnType("INTEGER")
                .HasColumnName("id");

            b.Property<int>("WorkdayBoundaryMinutes")
                .HasColumnType("INTEGER")
                .HasColumnName("workday_boundary_minutes");

            b.Property<string>("UpdatedAt")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_app_settings");

            b.ToTable("app_settings", null, t =>
            {
                t.HasCheckConstraint("ck_app_settings_singleton_id", "id = 1");
                t.HasCheckConstraint(
                    "ck_app_settings_workday_boundary",
                    "workday_boundary_minutes >= 0 AND workday_boundary_minutes <= 1439");
            });
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskEntity", b =>
        {
            b.Property<string>("Id")
                .HasColumnType("TEXT")
                .HasColumnName("id");

            b.Property<string>("ContinuedFromTaskId")
                .HasColumnType("TEXT")
                .HasColumnName("continued_from_task_id");

            b.Property<string>("CreatedAt")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("created_at");

            b.Property<string>("LocalDate")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("local_date");

            b.Property<long?>("RangeEnd")
                .HasColumnType("INTEGER")
                .HasColumnName("range_end");

            b.Property<long?>("RangeStart")
                .HasColumnType("INTEGER")
                .HasColumnName("range_start");

            b.Property<int?>("Result")
                .HasColumnType("INTEGER")
                .HasColumnName("result");

            b.Property<string>("ResultNote")
                .HasColumnType("TEXT")
                .HasColumnName("result_note");

            b.Property<string>("ResultRecordedAt")
                .HasColumnType("TEXT")
                .HasColumnName("result_recorded_at");

            b.Property<int>("SortOrder")
                .HasColumnType("INTEGER")
                .HasColumnName("sort_order");

            b.Property<long?>("TimePoint")
                .HasColumnType("INTEGER")
                .HasColumnName("time_point");

            b.Property<int>("TimeType")
                .HasColumnType("INTEGER")
                .HasColumnName("time_type");

            b.Property<string>("Title")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("title");

            b.Property<string>("UpdatedAt")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_tasks");

            b.HasIndex("ContinuedFromTaskId")
                .HasDatabaseName("ix_tasks_continued_from_task_id");

            b.ToTable("tasks", null, t =>
            {
                t.HasCheckConstraint("ck_tasks_id_uuid_v7", "length(id) = 36 AND id NOT GLOB '*[^0-9A-Fa-f-]*' AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-' AND lower(substr(id, 15, 1)) = '7' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b')");
                t.HasCheckConstraint("ck_tasks_partial_requires_range", "result IS NULL OR result <> 2 OR time_type = 2");
                t.HasCheckConstraint("ck_tasks_result_metadata", "(result IS NULL AND result_recorded_at IS NULL AND result_note IS NULL) OR (result IS NOT NULL AND result_recorded_at IS NOT NULL)");
                t.HasCheckConstraint("ck_tasks_result_timestamp_order", "result_recorded_at IS NULL OR (result_recorded_at >= created_at AND result_recorded_at <= updated_at)");
                t.HasCheckConstraint("ck_tasks_result_value", "result IS NULL OR result IN (0, 1, 2)");
                t.HasCheckConstraint("ck_tasks_sort_order_non_negative", "sort_order >= 0");
                t.HasCheckConstraint("ck_tasks_time_shape", "(time_type = 0 AND time_point IS NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 1 AND time_point IS NOT NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 2 AND time_point IS NULL AND range_start IS NOT NULL AND range_end IS NOT NULL AND range_start <> range_end)");
                t.HasCheckConstraint("ck_tasks_time_values", "(time_point IS NULL OR (time_point >= 0 AND time_point < 86400000000000)) AND (range_start IS NULL OR (range_start >= 0 AND range_start < 86400000000000)) AND (range_end IS NULL OR (range_end >= 0 AND range_end < 86400000000000))");
                t.HasCheckConstraint("ck_tasks_timestamp_order", "updated_at >= created_at");
                t.HasCheckConstraint("ck_tasks_continuation_not_self", "continued_from_task_id IS NULL OR continued_from_task_id <> id");
                t.HasCheckConstraint("ck_tasks_title_not_blank", "length(trim(title)) > 0");
            });
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskHistoryEntity", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasColumnName("id");

            b.Property<string>("ContinuedFromTaskId")
                .HasColumnType("TEXT")
                .HasColumnName("continued_from_task_id");

            b.Property<string>("CreatedAt")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("created_at");

            b.Property<int>("Kind")
                .HasColumnType("INTEGER")
                .HasColumnName("kind");

            b.Property<string>("LocalDate")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("local_date");

            b.Property<string>("OccurredAt")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("occurred_at");

            b.Property<long?>("RangeEnd")
                .HasColumnType("INTEGER")
                .HasColumnName("range_end");

            b.Property<long?>("RangeStart")
                .HasColumnType("INTEGER")
                .HasColumnName("range_start");

            b.Property<string>("RelatedTaskId")
                .HasColumnType("TEXT")
                .HasColumnName("related_task_id");

            b.Property<int?>("Result")
                .HasColumnType("INTEGER")
                .HasColumnName("result");

            b.Property<string>("ResultNote")
                .HasColumnType("TEXT")
                .HasColumnName("result_note");

            b.Property<string>("ResultRecordedAt")
                .HasColumnType("TEXT")
                .HasColumnName("result_recorded_at");

            b.Property<int>("SortOrder")
                .HasColumnType("INTEGER")
                .HasColumnName("sort_order");

            b.Property<string>("TaskId")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("task_id");

            b.Property<long?>("TimePoint")
                .HasColumnType("INTEGER")
                .HasColumnName("time_point");

            b.Property<int>("TimeType")
                .HasColumnType("INTEGER")
                .HasColumnName("time_type");

            b.Property<string>("Title")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("title");

            b.Property<string>("UpdatedAt")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_task_history");

            b.HasIndex("TaskId", "Id")
                .HasDatabaseName("ix_task_history_task_id_id");

            b.HasIndex("ContinuedFromTaskId")
                .HasDatabaseName("ix_task_history_continued_from_task_id");

            b.HasIndex("RelatedTaskId")
                .HasDatabaseName("ix_task_history_related_task_id");

            b.ToTable("task_history", null, t =>
            {
                t.HasCheckConstraint("ck_task_history_continuation_metadata", "(kind <> 2 AND related_task_id IS NULL) OR (kind = 2 AND related_task_id IS NOT NULL AND continued_from_task_id = related_task_id AND task_id <> related_task_id)");
                t.HasCheckConstraint("ck_task_history_id_uuid_v7", "length(task_id) = 36 AND task_id NOT GLOB '*[^0-9A-Fa-f-]*' AND substr(task_id, 9, 1) = '-' AND substr(task_id, 14, 1) = '-' AND substr(task_id, 19, 1) = '-' AND substr(task_id, 24, 1) = '-' AND lower(substr(task_id, 15, 1)) = '7' AND lower(substr(task_id, 20, 1)) IN ('8', '9', 'a', 'b')");
                t.HasCheckConstraint("ck_task_history_kind", "kind IN (0, 1, 2, 3, 4)");
                t.HasCheckConstraint("ck_task_history_partial_requires_range", "result IS NULL OR result <> 2 OR time_type = 2");
                t.HasCheckConstraint("ck_task_history_result_metadata", "(result IS NULL AND result_recorded_at IS NULL AND result_note IS NULL) OR (result IS NOT NULL AND result_recorded_at IS NOT NULL)");
                t.HasCheckConstraint("ck_task_history_result_timestamp_order", "result_recorded_at IS NULL OR (result_recorded_at >= created_at AND result_recorded_at <= updated_at)");
                t.HasCheckConstraint("ck_task_history_result_value", "result IS NULL OR result IN (0, 1, 2)");
                t.HasCheckConstraint("ck_task_history_sort_order_non_negative", "sort_order >= 0");
                t.HasCheckConstraint("ck_task_history_time_shape", "(time_type = 0 AND time_point IS NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 1 AND time_point IS NOT NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 2 AND time_point IS NULL AND range_start IS NOT NULL AND range_end IS NOT NULL AND range_start <> range_end)");
                t.HasCheckConstraint("ck_task_history_time_values", "(time_point IS NULL OR (time_point >= 0 AND time_point < 86400000000000)) AND (range_start IS NULL OR (range_start >= 0 AND range_start < 86400000000000)) AND (range_end IS NULL OR (range_end >= 0 AND range_end < 86400000000000))");
                t.HasCheckConstraint("ck_task_history_timestamp_order", "updated_at >= created_at AND occurred_at >= created_at");
                t.HasCheckConstraint("ck_task_history_title_not_blank", "length(trim(title)) > 0");
            });
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskHistoryEntity", b =>
        {
            b.HasOne("ReminNote.Infrastructure.Persistence.TaskEntity", null)
                .WithMany()
                .HasForeignKey("TaskId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("ReminNote.Infrastructure.Persistence.TaskEntity", null)
                .WithMany()
                .HasForeignKey("ContinuedFromTaskId")
                .OnDelete(DeleteBehavior.SetNull);

            b.HasOne("ReminNote.Infrastructure.Persistence.TaskEntity", null)
                .WithMany()
                .HasForeignKey("RelatedTaskId")
                .OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskEntity", b =>
        {
            b.HasOne("ReminNote.Infrastructure.Persistence.TaskEntity", null)
                .WithMany()
                .HasForeignKey("ContinuedFromTaskId")
                .OnDelete(DeleteBehavior.SetNull);
        });
#pragma warning restore 612, 618
    }
}
