// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ReminNote.Infrastructure.Persistence;

#nullable disable

namespace ReminNote.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ReminNoteDbContext))]
partial class ReminNoteDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.AppSettingsEntity", b =>
        {
            b.Property<int>("Id")
                .HasColumnType("INTEGER")
                .HasColumnName("id");

            b.Property<int>("WorkdayBoundaryMinutes")
                .HasColumnType("INTEGER")
                .HasColumnName("workday_boundary_minutes");

            b.Property<string>("UpdatedAt")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_app_settings");

            b.ToTable("app_settings", null, t =>
            {
                t.HasCheckConstraint("ck_app_settings_singleton_id", "id = 1");
                t.HasCheckConstraint(
                    "ck_app_settings_workday_boundary",
                    "workday_boundary_minutes >= 0 AND workday_boundary_minutes <= 1439");
            });
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.P25.P25RevisionStateEntity", b =>
        {
            b.Property<string>("ProfileScope")
                .HasMaxLength(67)
                .HasColumnType("TEXT")
                .HasColumnName("profile_scope");

            b.Property<long>("CurrentRevision")
                .HasColumnType("INTEGER")
                .HasColumnName("current_revision");

            b.Property<long>("OldestAvailableRevision")
                .HasColumnType("INTEGER")
                .HasColumnName("oldest_available_revision");

            b.HasKey("ProfileScope")
                .HasName("pk_revision_state");

            b.ToTable("revision_state", null, t =>
            {
                t.HasCheckConstraint("ck_revision_state_current_revision", "current_revision >= 0");
                t.HasCheckConstraint("ck_revision_state_oldest_revision", "oldest_available_revision >= 0");
                t.HasCheckConstraint("ck_revision_state_revision_order", "oldest_available_revision = 0 OR oldest_available_revision <= current_revision");
            });
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.P25.P25ChangeJournalEntity", b =>
        {
            b.Property<string>("ProfileScope")
                .HasMaxLength(67)
                .HasColumnType("TEXT")
                .HasColumnName("profile_scope");

            b.Property<long>("Revision")
                .HasColumnType("INTEGER")
                .HasColumnName("revision");

            b.Property<long>("ChangeOrdinal")
                .HasColumnType("INTEGER")
                .HasColumnName("change_ordinal");

            b.Property<string>("BatchId")
                .IsRequired()
                .HasMaxLength(96)
                .HasColumnType("TEXT")
                .HasColumnName("batch_id");

            b.Property<string>("EntityType")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("TEXT")
                .HasColumnName("entity_type");

            b.Property<string>("EntityId")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("TEXT")
                .HasColumnName("entity_id");

            b.Property<string>("ChangeKind")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("TEXT")
                .HasColumnName("change_kind");

            b.Property<string>("ChangedAtUtc")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("TEXT")
                .HasColumnName("changed_at_utc");

            b.HasKey("ProfileScope", "Revision", "ChangeOrdinal")
                .HasName("pk_change_journal");

            b.HasIndex("ProfileScope", "Revision", "ChangeOrdinal")
                .HasDatabaseName("ix_change_journal_profile_revision");

            b.ToTable("change_journal", null, t =>
            {
                t.HasCheckConstraint("ck_change_journal_revision", "revision > 0");
                t.HasCheckConstraint("ck_change_journal_ordinal", "change_ordinal >= 0");
                t.HasCheckConstraint("ck_change_journal_batch_id", "length(batch_id) BETWEEN 1 AND 96");
                t.HasCheckConstraint("ck_change_journal_entity_type", "length(entity_type) BETWEEN 1 AND 128");
                t.HasCheckConstraint("ck_change_journal_entity_id", "length(entity_id) BETWEEN 1 AND 256");
                t.HasCheckConstraint("ck_change_journal_change_kind", "length(change_kind) BETWEEN 1 AND 64");
                t.HasCheckConstraint("ck_change_journal_changed_at", "length(changed_at_utc) BETWEEN 1 AND 64");
            });
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.P25.P25CommandReceiptEntity", b =>
        {
            b.Property<string>("ActualUserSid")
                .HasMaxLength(256)
                .HasColumnType("TEXT")
                .HasColumnName("actual_user_sid");

            b.Property<string>("ProfileScope")
                .HasMaxLength(67)
                .HasColumnType("TEXT")
                .HasColumnName("profile_scope");

            b.Property<string>("IdempotencyKey")
                .HasMaxLength(36)
                .HasColumnType("TEXT")
                .HasColumnName("idempotency_key");

            b.Property<string>("Operation")
                .IsRequired()
                .HasMaxLength(96)
                .HasColumnType("TEXT")
                .HasColumnName("operation");

            b.Property<string>("HashVersion")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("TEXT")
                .HasColumnName("hash_version");

            b.Property<byte[]>("CanonicalPayloadHash")
                .IsRequired()
                .HasColumnType("BLOB")
                .HasColumnName("canonical_payload_hash");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("TEXT")
                .HasColumnName("status");

            b.Property<bool>("Changed")
                .HasColumnType("INTEGER")
                .HasColumnName("changed");

            b.Property<long?>("CommittedRevision")
                .HasColumnType("INTEGER")
                .HasColumnName("committed_revision");

            b.Property<string>("ErrorCode")
                .HasMaxLength(160)
                .HasColumnType("TEXT")
                .HasColumnName("error_code");

            b.Property<string>("FirstAcceptedAtUtc")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("TEXT")
                .HasColumnName("first_accepted_at_utc");

            b.Property<string>("UpdatedAtUtc")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("TEXT")
                .HasColumnName("updated_at_utc");

            b.Property<string>("FirstRequestId")
                .IsRequired()
                .HasMaxLength(36)
                .HasColumnType("TEXT")
                .HasColumnName("first_request_id");

            b.Property<string>("LastRequestId")
                .IsRequired()
                .HasMaxLength(36)
                .HasColumnType("TEXT")
                .HasColumnName("last_request_id");

            b.Property<int>("AttemptCount")
                .HasColumnType("INTEGER")
                .HasColumnName("attempt_count");

            b.Property<string>("AgentInstanceId")
                .HasMaxLength(36)
                .HasColumnType("TEXT")
                .HasColumnName("agent_instance_id");

            b.HasKey("ActualUserSid", "ProfileScope", "IdempotencyKey")
                .HasName("pk_command_receipt");

            b.HasIndex("ProfileScope", "IdempotencyKey")
                .HasDatabaseName("ix_command_receipt_profile_key");

            b.ToTable("command_receipt", null, t =>
            {
                t.HasCheckConstraint("ck_command_receipt_sid", "length(actual_user_sid) BETWEEN 1 AND 256");
                t.HasCheckConstraint("ck_command_receipt_idempotency_key", "length(idempotency_key) = 36");
                t.HasCheckConstraint("ck_command_receipt_operation", "length(operation) BETWEEN 1 AND 96");
                t.HasCheckConstraint("ck_command_receipt_hash_version", "length(hash_version) BETWEEN 1 AND 32");
                t.HasCheckConstraint("ck_command_receipt_hash", "length(canonical_payload_hash) = 32");
                t.HasCheckConstraint("ck_command_receipt_status", "status IN ('PENDING','COMMITTED','REJECTED_STALE','REJECTED','ROLLED_BACK','CANCELLED','TIMED_OUT','UNKNOWN')");
                t.HasCheckConstraint("ck_command_receipt_changed", "changed IN (0, 1)");
                t.HasCheckConstraint("ck_command_receipt_committed_revision", "committed_revision IS NULL OR committed_revision >= 0");
                t.HasCheckConstraint("ck_command_receipt_error_code", "error_code IS NULL OR length(error_code) BETWEEN 1 AND 160");
                t.HasCheckConstraint("ck_command_receipt_first_accepted", "length(first_accepted_at_utc) BETWEEN 1 AND 64");
                t.HasCheckConstraint("ck_command_receipt_updated", "length(updated_at_utc) BETWEEN 1 AND 64");
                t.HasCheckConstraint("ck_command_receipt_first_request_id", "length(first_request_id) = 36");
                t.HasCheckConstraint("ck_command_receipt_last_request_id", "length(last_request_id) = 36");
                t.HasCheckConstraint("ck_command_receipt_attempt_count", "attempt_count BETWEEN 1 AND 2");
                t.HasCheckConstraint("ck_command_receipt_agent_instance_id", "agent_instance_id IS NULL OR length(agent_instance_id) = 36");
            });
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskEntity", b =>
        {
            b.Property<string>("Id")
                .HasColumnType("TEXT")
                .HasColumnName("id");

            b.Property<string>("ContinuedFromTaskId")
                .HasColumnType("TEXT")
                .HasColumnName("continued_from_task_id");

            b.Property<string>("CreatedAt")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("created_at");

            b.Property<string>("LocalDate")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("local_date");

            b.Property<long?>("RangeEnd")
                .HasColumnType("INTEGER")
                .HasColumnName("range_end");

            b.Property<long?>("RangeStart")
                .HasColumnType("INTEGER")
                .HasColumnName("range_start");

            b.Property<int?>("Result")
                .HasColumnType("INTEGER")
                .HasColumnName("result");

            b.Property<string>("ResultNote")
                .HasColumnType("TEXT")
                .HasColumnName("result_note");

            b.Property<string>("ResultRecordedAt")
                .HasColumnType("TEXT")
                .HasColumnName("result_recorded_at");

            b.Property<int>("SortOrder")
                .HasColumnType("INTEGER")
                .HasColumnName("sort_order");

            b.Property<long?>("TimePoint")
                .HasColumnType("INTEGER")
                .HasColumnName("time_point");

            b.Property<int>("TimeType")
                .HasColumnType("INTEGER")
                .HasColumnName("time_type");

            b.Property<string>("Title")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("title");

            b.Property<string>("UpdatedAt")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_tasks");

            b.HasIndex("ContinuedFromTaskId")
                .HasDatabaseName("ix_tasks_continued_from_task_id");

            b.ToTable("tasks", null, t =>
            {
                t.HasCheckConstraint("ck_tasks_id_uuid_v7", "length(id) = 36 AND id NOT GLOB '*[^0-9A-Fa-f-]*' AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-' AND lower(substr(id, 15, 1)) = '7' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b')");
                t.HasCheckConstraint("ck_tasks_partial_requires_range", "result IS NULL OR result <> 2 OR time_type = 2");
                t.HasCheckConstraint("ck_tasks_result_metadata", "(result IS NULL AND result_recorded_at IS NULL AND result_note IS NULL) OR (result IS NOT NULL AND result_recorded_at IS NOT NULL)");
                t.HasCheckConstraint("ck_tasks_result_timestamp_order", "result_recorded_at IS NULL OR (result_recorded_at >= created_at AND result_recorded_at <= updated_at)");
                t.HasCheckConstraint("ck_tasks_result_value", "result IS NULL OR result IN (0, 1, 2)");
                t.HasCheckConstraint("ck_tasks_sort_order_non_negative", "sort_order >= 0");
                t.HasCheckConstraint("ck_tasks_time_shape", "(time_type = 0 AND time_point IS NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 1 AND time_point IS NOT NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 2 AND time_point IS NULL AND range_start IS NOT NULL AND range_end IS NOT NULL AND range_start <> range_end)");
                t.HasCheckConstraint("ck_tasks_time_values", "(time_point IS NULL OR (time_point >= 0 AND time_point < 86400000000000)) AND (range_start IS NULL OR (range_start >= 0 AND range_start < 86400000000000)) AND (range_end IS NULL OR (range_end >= 0 AND range_end < 86400000000000))");
                t.HasCheckConstraint("ck_tasks_timestamp_order", "updated_at >= created_at");
                t.HasCheckConstraint("ck_tasks_continuation_not_self", "continued_from_task_id IS NULL OR continued_from_task_id <> id");
                t.HasCheckConstraint("ck_tasks_title_not_blank", "length(trim(title)) > 0");
            });
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskHistoryEntity", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasColumnName("id");

            b.Property<string>("ContinuedFromTaskId")
                .HasColumnType("TEXT")
                .HasColumnName("continued_from_task_id");

            b.Property<string>("CreatedAt")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("created_at");

            b.Property<int>("Kind")
                .HasColumnType("INTEGER")
                .HasColumnName("kind");

            b.Property<string>("LocalDate")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("local_date");

            b.Property<string>("OccurredAt")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("occurred_at");

            b.Property<long?>("RangeEnd")
                .HasColumnType("INTEGER")
                .HasColumnName("range_end");

            b.Property<long?>("RangeStart")
                .HasColumnType("INTEGER")
                .HasColumnName("range_start");

            b.Property<string>("RelatedTaskId")
                .HasColumnType("TEXT")
                .HasColumnName("related_task_id");

            b.Property<int?>("Result")
                .HasColumnType("INTEGER")
                .HasColumnName("result");

            b.Property<string>("ResultNote")
                .HasColumnType("TEXT")
                .HasColumnName("result_note");

            b.Property<string>("ResultRecordedAt")
                .HasColumnType("TEXT")
                .HasColumnName("result_recorded_at");

            b.Property<int>("SortOrder")
                .HasColumnType("INTEGER")
                .HasColumnName("sort_order");

            b.Property<string>("TaskId")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("task_id");

            b.Property<long?>("TimePoint")
                .HasColumnType("INTEGER")
                .HasColumnName("time_point");

            b.Property<int>("TimeType")
                .HasColumnType("INTEGER")
                .HasColumnName("time_type");

            b.Property<string>("Title")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("title");

            b.Property<string>("UpdatedAt")
                .IsRequired()
                .HasColumnType("TEXT")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_task_history");

            b.HasIndex("TaskId", "Id")
                .HasDatabaseName("ix_task_history_task_id_id");

            b.HasIndex("ContinuedFromTaskId")
                .HasDatabaseName("ix_task_history_continued_from_task_id");

            b.HasIndex("RelatedTaskId")
                .HasDatabaseName("ix_task_history_related_task_id");

            b.ToTable("task_history", null, t =>
            {
                t.HasCheckConstraint("ck_task_history_continuation_metadata", "(kind <> 2 AND related_task_id IS NULL) OR (kind = 2 AND related_task_id IS NOT NULL AND continued_from_task_id = related_task_id AND task_id <> related_task_id)");
                t.HasCheckConstraint("ck_task_history_id_uuid_v7", "length(task_id) = 36 AND task_id NOT GLOB '*[^0-9A-Fa-f-]*' AND substr(task_id, 9, 1) = '-' AND substr(task_id, 14, 1) = '-' AND substr(task_id, 19, 1) = '-' AND substr(task_id, 24, 1) = '-' AND lower(substr(task_id, 15, 1)) = '7' AND lower(substr(task_id, 20, 1)) IN ('8', '9', 'a', 'b')");
                t.HasCheckConstraint("ck_task_history_kind", "kind IN (0, 1, 2, 3, 4)");
                t.HasCheckConstraint("ck_task_history_partial_requires_range", "result IS NULL OR result <> 2 OR time_type = 2");
                t.HasCheckConstraint("ck_task_history_result_metadata", "(result IS NULL AND result_recorded_at IS NULL AND result_note IS NULL) OR (result IS NOT NULL AND result_recorded_at IS NOT NULL)");
                t.HasCheckConstraint("ck_task_history_result_timestamp_order", "result_recorded_at IS NULL OR (result_recorded_at >= created_at AND result_recorded_at <= updated_at)");
                t.HasCheckConstraint("ck_task_history_result_value", "result IS NULL OR result IN (0, 1, 2)");
                t.HasCheckConstraint("ck_task_history_sort_order_non_negative", "sort_order >= 0");
                t.HasCheckConstraint("ck_task_history_time_shape", "(time_type = 0 AND time_point IS NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 1 AND time_point IS NOT NULL AND range_start IS NULL AND range_end IS NULL) OR (time_type = 2 AND time_point IS NULL AND range_start IS NOT NULL AND range_end IS NOT NULL AND range_start <> range_end)");
                t.HasCheckConstraint("ck_task_history_time_values", "(time_point IS NULL OR (time_point >= 0 AND time_point < 86400000000000)) AND (range_start IS NULL OR (range_start >= 0 AND range_start < 86400000000000)) AND (range_end IS NULL OR (range_end >= 0 AND range_end < 86400000000000))");
                t.HasCheckConstraint("ck_task_history_timestamp_order", "updated_at >= created_at AND occurred_at >= created_at");
                t.HasCheckConstraint("ck_task_history_title_not_blank", "length(trim(title)) > 0");
            });
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskHistoryEntity", b =>
        {
            b.HasOne("ReminNote.Infrastructure.Persistence.TaskEntity", null)
                .WithMany()
                .HasForeignKey("TaskId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("ReminNote.Infrastructure.Persistence.TaskEntity", null)
                .WithMany()
                .HasForeignKey("ContinuedFromTaskId")
                .OnDelete(DeleteBehavior.SetNull);

            b.HasOne("ReminNote.Infrastructure.Persistence.TaskEntity", null)
                .WithMany()
                .HasForeignKey("RelatedTaskId")
                .OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.TaskEntity", b =>
        {
            b.HasOne("ReminNote.Infrastructure.Persistence.TaskEntity", null)
                .WithMany()
                .HasForeignKey("ContinuedFromTaskId")
                .OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.P25.P25ChangeJournalEntity", b =>
        {
            b.HasOne("ReminNote.Infrastructure.Persistence.P25.P25RevisionStateEntity", null)
                .WithMany()
                .HasForeignKey("ProfileScope")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("ReminNote.Infrastructure.Persistence.P25.P25CommandReceiptEntity", b =>
        {
            b.HasOne("ReminNote.Infrastructure.Persistence.P25.P25RevisionStateEntity", null)
                .WithMany()
                .HasForeignKey("ProfileScope")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
