<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ReminNote.Infrastructure</RootNamespace>
    <AssemblyName>ReminNote.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReminNote.Core\ReminNote.Core.csproj" />
  </ItemGroup>
</Project>
