using System.Globalization;
using System.Resources;
using System.Collections.Concurrent;
using System.Text;

namespace ReminNote.Windows.Resources.Localization;

/// <summary>
/// Stable UI resource keys for the P0 default language.
/// </summary>
public static class UiText
{
    private const string ResourceBaseName = "ReminNote.Windows.Resources.Localization.UiText";
    private const string MissingResourceFormat = "[Missing resource: {0}]";
    private static readonly ResourceManager ResourceManager = new(ResourceBaseName, typeof(UiText).Assembly);
    private static readonly CompositeFormat MissingResourceCompositeFormat = CompositeFormat.Parse(MissingResourceFormat);
    private static readonly ConcurrentDictionary<string, CompositeFormat> CompositeFormats = new(StringComparer.Ordinal);

    public const string ShellWindowTitleKey = "Shell.WindowTitle";
    public const string ShellBrandNameKey = "Shell.BrandName";
    public const string ShellBrandSubtitleKey = "Shell.BrandSubtitle";
    public const string ShellStageLabelKey = "Shell.StageLabel";
    public const string ShellHeaderSubtitleKey = "Shell.HeaderSubtitle";
    public const string ShellFooterKey = "Shell.Footer";
    public const string ShellNavigationKey = "Shell.Navigation";
    public const string ShellPageNavigationKey = "Shell.PageNavigation";
    public const string ShellHeaderRegionKey = "Shell.HeaderRegion";
    public const string ShellMainContentKey = "Shell.MainContent";
    public const string ShellStatusRegionKey = "Shell.StatusRegion";
    public const string ShellTodayTitleKey = "Shell.TodayTitle";
    public const string ShellTodaySubtitleKey = "Shell.TodaySubtitle";
    public const string ShellAnimeTitleKey = "Shell.AnimeTitle";
    public const string ShellAnimeSubtitleKey = "Shell.AnimeSubtitle";
    public const string ShellFallbackTitleKey = "Shell.FallbackTitle";

    public const string TodayPageDescriptionKey = "Today.PageDescription";
    public const string TodayMockBadgeKey = "Today.MockBadge";
    public const string TodayNeedsReviewTextKey = "Today.NeedsReviewText";
    public const string TodayNeedsReviewNoneKey = "Today.NeedsReviewNone";
    public const string TodayNeedsReviewPendingKey = "Today.NeedsReviewPending";
    public const string TodayPlanSummaryKey = "Today.PlanSummary";
    public const string TodayQuickAddKey = "Today.QuickAdd";
    public const string TodayQuickAddDescriptionKey = "Today.QuickAddDescription";
    public const string TodayQuickAddToolTipKey = "Today.QuickAddToolTip";
    public const string TodayAddToTodayKey = "Today.AddToToday";
    public const string CommonCancelKey = "Common.Cancel";
    public const string CommonViewDetailsKey = "Common.ViewDetails";
    public const string CommonAutomationContextKey = "Common.AutomationContext";
    public const string TodayPrimaryFocusKey = "Today.PrimaryFocus";
    public const string TodayReviewQueueKey = "Today.ReviewQueue";
    public const string TodayPlanMetricKey = "Today.PlanMetric";
    public const string TodayViewNeedsReviewKey = "Today.ViewNeedsReview";
    public const string TodayPlanKey = "Today.Plan";
    public const string TodayDetailsKey = "Today.Details";
    public const string TodayTimeShapeKey = "Today.TimeShape";
    public const string TodayPriorityKey = "Today.Priority";
    public const string TodayRangeNeedsResultKey = "Today.RangeNeedsResult";
    public const string TodayItemsKey = "Today.Items";
    public const string TodayGroupOverdueTitleKey = "Today.GroupOverdueTitle";
    public const string TodayGroupOverdueSubtitleKey = "Today.GroupOverdueSubtitle";
    public const string TodayGroupMorningTitleKey = "Today.GroupMorningTitle";
    public const string TodayGroupMorningSubtitleKey = "Today.GroupMorningSubtitle";
    public const string TodayGroupAfternoonTitleKey = "Today.GroupAfternoonTitle";
    public const string TodayGroupAfternoonSubtitleKey = "Today.GroupAfternoonSubtitle";
    public const string TodayGroupEveningTitleKey = "Today.GroupEveningTitle";
    public const string TodayGroupEveningSubtitleKey = "Today.GroupEveningSubtitle";
    public const string TodayGroupAnytimeTitleKey = "Today.GroupAnytimeTitle";
    public const string TodayGroupAnytimeSubtitleKey = "Today.GroupAnytimeSubtitle";
    public const string TodayGroupCompletedTitleKey = "Today.GroupCompletedTitle";
    public const string TodayGroupCompletedSubtitleKey = "Today.GroupCompletedSubtitle";
    public const string TodayInteractionLoadedKey = "Today.InteractionLoaded";
    public const string TodayInteractionQuickAddOpenedKey = "Today.InteractionQuickAddOpened";
    public const string TodayInteractionQuickAddCancelledKey = "Today.InteractionQuickAddCancelled";
    public const string TodayInteractionQuickAddEmptyKey = "Today.InteractionQuickAddEmpty";
    public const string TodayInteractionQuickAddAddedKey = "Today.InteractionQuickAddAdded";
    public const string TodayInteractionNoReviewKey = "Today.InteractionNoReview";
    public const string TodayInteractionReviewLocatedKey = "Today.InteractionReviewLocated";
    public const string TodayInteractionCompletedKey = "Today.InteractionCompleted";
    public const string TodayInteractionRestoredKey = "Today.InteractionRestored";
    public const string TodayInteractionPinnedKey = "Today.InteractionPinned";
    public const string TodayInteractionUnpinnedKey = "Today.InteractionUnpinned";
    public const string TodayStatusOverdueKey = "Today.StatusOverdue";
    public const string TodayStatusCompletedKey = "Today.StatusCompleted";
    public const string TodayStatusUpcomingKey = "Today.StatusUpcoming";
    public const string TodayStatusAwaitingResultKey = "Today.StatusAwaitingResult";
    public const string TodayStatusPlannedKey = "Today.StatusPlanned";
    public const string TodayStatusDescriptionCompletedKey = "Today.StatusDescriptionCompleted";
    public const string TodayStatusDescriptionReviewKey = "Today.StatusDescriptionReview";
    public const string TodayStatusDescriptionPlannedKey = "Today.StatusDescriptionPlanned";
    public const string TodayMarkCompleteKey = "Today.MarkComplete";
    public const string TodayRestoreIncompleteKey = "Today.RestoreIncomplete";
    public const string TodayPinKey = "Today.Pin";
    public const string TodayUnpinKey = "Today.Unpin";
    public const string TodayNeedsReviewLabelKey = "Today.NeedsReviewLabel";

    public const string AnimePageDescriptionKey = "Anime.PageDescription";
    public const string AnimeMockBadgeKey = "Anime.MockBadge";
    public const string AnimeSearchToolTipKey = "Anime.SearchToolTip";
    public const string AnimeSearchAutomationNameKey = "Anime.SearchAutomationName";
    public const string AnimeClearSearchKey = "Anime.ClearSearch";
    public const string AnimeNextAiringKey = "Anime.NextAiring";
    public const string AnimeViewDetailsKey = "Anime.ViewDetails";
    public const string AnimeCountdownKey = "Anime.Countdown";
    public const string AnimeStaticDemoTimeKey = "Anime.StaticDemoTime";
    public const string AnimeThisSeasonKey = "Anime.ThisSeason";
    public const string AnimeSeasonSummaryKey = "Anime.SeasonSummary";
    public const string AnimeOpenSeasonKey = "Anime.OpenSeason";
    public const string AnimeSelectedAnimeKey = "Anime.SelectedAnime";
    public const string AnimeMockStatusKey = "Anime.MockStatus";
    public const string AnimeReloadMockKey = "Anime.ReloadMock";
    public const string AnimeSectionAllLabelKey = "Anime.SectionAllLabel";
    public const string AnimeSectionAllEnglishKey = "Anime.SectionAllEnglish";
    public const string AnimeSectionThisSeasonLabelKey = "Anime.SectionThisSeasonLabel";
    public const string AnimeSectionThisSeasonEnglishKey = "Anime.SectionThisSeasonEnglish";
    public const string AnimeSectionWatchingLabelKey = "Anime.SectionWatchingLabel";
    public const string AnimeSectionWatchingEnglishKey = "Anime.SectionWatchingEnglish";
    public const string AnimeSectionWatchLaterLabelKey = "Anime.SectionWatchLaterLabel";
    public const string AnimeSectionWatchLaterEnglishKey = "Anime.SectionWatchLaterEnglish";
    public const string AnimeSectionPlanToWatchLabelKey = "Anime.SectionPlanToWatchLabel";
    public const string AnimeSectionPlanToWatchEnglishKey = "Anime.SectionPlanToWatchEnglish";
    public const string AnimeSectionAllDescriptionKey = "Anime.SectionAllDescription";
    public const string AnimeSectionThisSeasonDescriptionKey = "Anime.SectionThisSeasonDescription";
    public const string AnimeSectionWatchingDescriptionKey = "Anime.SectionWatchingDescription";
    public const string AnimeSectionWatchLaterDescriptionKey = "Anime.SectionWatchLaterDescription";
    public const string AnimeSectionPlanToWatchDescriptionKey = "Anime.SectionPlanToWatchDescription";
    public const string AnimeNoSelectedTitleKey = "Anime.NoSelectedTitle";
    public const string AnimeNoSelectedSubtitleKey = "Anime.NoSelectedSubtitle";
    public const string AnimeNoSelectedDescriptionKey = "Anime.NoSelectedDescription";
    public const string AnimeNoSelectedStatusKey = "Anime.NoSelectedStatus";
    public const string AnimeNoSelectedProgressKey = "Anime.NoSelectedProgress";
    public const string AnimeVisibleCountKey = "Anime.VisibleCount";
    public const string AnimeEmptyTitleKey = "Anime.EmptyTitle";
    public const string AnimeEmptySearchTitleKey = "Anime.EmptySearchTitle";
    public const string AnimeEmptyDescriptionKey = "Anime.EmptyDescription";
    public const string AnimeEmptySearchDescriptionKey = "Anime.EmptySearchDescription";
    public const string AnimeInteractionSelectedKey = "Anime.InteractionSelected";
    public const string AnimeInteractionWatchLaterAddedKey = "Anime.InteractionWatchLaterAdded";
    public const string AnimeInteractionWatchLaterRemovedKey = "Anime.InteractionWatchLaterRemoved";
    public const string AnimeInteractionWatchedKey = "Anime.InteractionWatched";
    public const string AnimeInteractionTrackingOnKey = "Anime.InteractionTrackingOn";
    public const string AnimeInteractionTrackingOffKey = "Anime.InteractionTrackingOff";
    public const string AnimeInteractionReminderOnKey = "Anime.InteractionReminderOn";
    public const string AnimeInteractionReminderOffKey = "Anime.InteractionReminderOff";
    public const string AnimeInteractionRefreshKey = "Anime.InteractionRefresh";
    public const string AnimeStatusWatchedKey = "Anime.StatusWatched";
    public const string AnimeStatusWatchLaterKey = "Anime.StatusWatchLater";
    public const string AnimeStatusTrackingKey = "Anime.StatusTracking";
    public const string AnimeStatusPlanToWatchKey = "Anime.StatusPlanToWatch";
    public const string AnimeStatusUnclassifiedKey = "Anime.StatusUnclassified";
    public const string AnimeStatusDetailWatchedKey = "Anime.StatusDetailWatched";
    public const string AnimeStatusDetailWatchLaterKey = "Anime.StatusDetailWatchLater";
    public const string AnimeStatusDetailTrackingKey = "Anime.StatusDetailTracking";
    public const string AnimeStatusDetailPlanToWatchKey = "Anime.StatusDetailPlanToWatch";
    public const string AnimeStatusDetailLocalKey = "Anime.StatusDetailLocal";
    public const string AnimeAiringWatchedKey = "Anime.AiringWatched";
    public const string AnimeAiringWatchLaterKey = "Anime.AiringWatchLater";
    public const string AnimeAiringNextKey = "Anime.AiringNext";
    public const string AnimeWatchLaterAddKey = "Anime.WatchLaterAdd";
    public const string AnimeWatchLaterRemoveKey = "Anime.WatchLaterRemove";
    public const string AnimeTrackingEnableKey = "Anime.TrackingEnable";
    public const string AnimeTrackingDisableKey = "Anime.TrackingDisable";
    public const string AnimeReminderOnKey = "Anime.ReminderOn";
    public const string AnimeReminderOffKey = "Anime.ReminderOff";
    public const string AnimeReminderStatusOnKey = "Anime.ReminderStatusOn";
    public const string AnimeReminderStatusOffKey = "Anime.ReminderStatusOff";
    public const string AnimeWatchedKey = "Anime.Watched";
    public const string AnimeProgressKey = "Anime.Progress";
    public const string AnimeMarkWatchedKey = "Anime.MarkWatched";

    public const string WidgetWindowTitleKey = "Widget.WindowTitle";
    public const string WidgetSubtitleKey = "Widget.Subtitle";
    public const string WidgetHeaderRegionKey = "Widget.HeaderRegion";
    public const string WidgetStateToolTipKey = "Widget.StateToolTip";
    public const string WidgetCloseKey = "Widget.Close";
    public const string WidgetExpandedLayoutKey = "Widget.ExpandedLayout";
    public const string WidgetTodayTabKey = "Widget.TodayTab";
    public const string WidgetAnimeTabKey = "Widget.AnimeTab";
    public const string WidgetPrimaryNextUpKey = "Widget.PrimaryNextUp";
    public const string WidgetNowKey = "Widget.Now";
    public const string WidgetUpcomingKey = "Widget.Upcoming";
    public const string WidgetSummaryKey = "Widget.Summary";
    public const string WidgetTodaySummaryFullKey = "Widget.TodaySummaryFull";
    public const string WidgetTodaySummaryCompactKey = "Widget.TodaySummaryCompact";
    public const string WidgetCompleteKey = "Widget.Complete";
    public const string WidgetSnoozeKey = "Widget.Snooze";
    public const string WidgetRescheduleKey = "Widget.Reschedule";
    public const string WidgetPrimaryNextAiringKey = "Widget.PrimaryNextAiring";
    public const string WidgetTonightKey = "Widget.Tonight";
    public const string WidgetWatchedKey = "Widget.Watched";
    public const string WidgetWatchLaterKey = "Widget.WatchLater";
    public const string WidgetScheduleTaskKey = "Widget.ScheduleTask";
    public const string WidgetFooterLocalMockKey = "Widget.FooterLocalMock";
    public const string WidgetQuickAddKey = "Widget.QuickAdd";
    public const string WidgetRemindersKey = "Widget.Reminders";
    public const string WidgetSimulateReminderKey = "Widget.SimulateReminder";
    public const string WidgetHighPriorityKey = "Widget.HighPriority";
    public const string WidgetAlertTitleKey = "Widget.AlertTitle";
    public const string WidgetAlertBodyKey = "Widget.AlertBody";
    public const string WidgetCurrentPageKey = "Widget.CurrentPage";
    public const string WidgetOpenReminderDrawerKey = "Widget.OpenReminderDrawer";
    public const string WidgetDismissAlertKey = "Widget.DismissAlert";
    public const string WidgetQuickAddHeadingKey = "Widget.QuickAddHeading";
    public const string WidgetQuickAddDescriptionKey = "Widget.QuickAddDescription";
    public const string WidgetQuickAddToolTipKey = "Widget.QuickAddToolTip";
    public const string WidgetAddKey = "Widget.Add";
    public const string WidgetQuickAddFeedbackKey = "Widget.QuickAddFeedback";
    public const string WidgetReminderDrawerHeadingKey = "Widget.ReminderDrawerHeading";
    public const string WidgetReminderDrawerTitleKey = "Widget.ReminderDrawerTitle";
    public const string WidgetTaskReminderMetaKey = "Widget.TaskReminderMeta";
    public const string WidgetUnreadKey = "Widget.Unread";
    public const string WidgetAnimeReminderTitleKey = "Widget.AnimeReminderTitle";
    public const string WidgetAnimeReminderMetaKey = "Widget.AnimeReminderMeta";
    public const string WidgetPendingKey = "Widget.Pending";
    public const string WidgetMarkReminderReadKey = "Widget.MarkReminderRead";
    public const string WidgetStateLockedKey = "Widget.StateLocked";
    public const string WidgetStateTempKey = "Widget.StateTemp";
    public const string WidgetStateUnlockedKey = "Widget.StateUnlocked";
    public const string WidgetStateAlertKey = "Widget.StateAlert";
    public const string WidgetStateMockKey = "Widget.StateMock";
    public const string WidgetTaskCompletedKey = "Widget.TaskCompleted";
    public const string WidgetTaskAnytimeKey = "Widget.TaskAnytime";
    public const string WidgetTaskCompletedFeedbackKey = "Widget.TaskCompletedFeedback";
    public const string WidgetTaskSnoozedFeedbackKey = "Widget.TaskSnoozedFeedback";
    public const string WidgetTaskRescheduledFeedbackKey = "Widget.TaskRescheduledFeedback";
    public const string WidgetAnimeWatchedFeedbackKey = "Widget.AnimeWatchedFeedback";
    public const string WidgetAnimeWatchLaterFeedbackKey = "Widget.AnimeWatchLaterFeedback";
    public const string WidgetAnimeScheduledFeedbackKey = "Widget.AnimeScheduledFeedback";
    public const string WidgetReminderReadFeedbackKey = "Widget.ReminderReadFeedback";
    public const string WidgetTodayHealthMetaKey = "Widget.TodayHealthMeta";
    public const string WidgetTodayReviewMetaKey = "Widget.TodayReviewMeta";
    public const string WidgetAnimeWatchingMetaKey = "Widget.AnimeWatchingMeta";
    public const string WidgetAnimeWatchLaterMetaKey = "Widget.AnimeWatchLaterMeta";
    public const string WidgetTodayPageSubtitleKey = "Widget.TodayPageSubtitle";
    public const string WidgetAnimePageSubtitleKey = "Widget.AnimePageSubtitle";

    public static string ShellWindowTitle => Get(ShellWindowTitleKey);
    public static string ShellBrandName => Get(ShellBrandNameKey);
    public static string ShellBrandSubtitle => Get(ShellBrandSubtitleKey);
    public static string ShellStageLabel => Get(ShellStageLabelKey);
    public static string ShellHeaderSubtitle => Get(ShellHeaderSubtitleKey);
    public static string ShellFooter => Get(ShellFooterKey);
    public static string ShellNavigation => Get(ShellNavigationKey);
    public static string ShellPageNavigation => Get(ShellPageNavigationKey);
    public static string ShellHeaderRegion => Get(ShellHeaderRegionKey);
    public static string ShellMainContent => Get(ShellMainContentKey);
    public static string ShellStatusRegion => Get(ShellStatusRegionKey);
    public static string ShellTodayTitle => Get(ShellTodayTitleKey);
    public static string ShellTodaySubtitle => Get(ShellTodaySubtitleKey);
    public static string ShellAnimeTitle => Get(ShellAnimeTitleKey);
    public static string ShellAnimeSubtitle => Get(ShellAnimeSubtitleKey);
    public static string ShellFallbackTitle => Get(ShellFallbackTitleKey);

    public static string TodayPageDescription => Get(TodayPageDescriptionKey);
    public static string TodayMockBadge => Get(TodayMockBadgeKey);
    public static string TodayQuickAdd => Get(TodayQuickAddKey);
    public static string TodayQuickAddDescription => Get(TodayQuickAddDescriptionKey);
    public static string TodayQuickAddToolTip => Get(TodayQuickAddToolTipKey);
    public static string TodayAddToToday => Get(TodayAddToTodayKey);
    public static string CommonCancel => Get(CommonCancelKey);
    public static string CommonViewDetails => Get(CommonViewDetailsKey);
    public static string CommonAutomationContext => Get(CommonAutomationContextKey);
    public static string TodayPrimaryFocus => Get(TodayPrimaryFocusKey);
    public static string TodayReviewQueue => Get(TodayReviewQueueKey);
    public static string TodayPlanMetric => Get(TodayPlanMetricKey);
    public static string TodayViewNeedsReview => Get(TodayViewNeedsReviewKey);
    public static string TodayPlan => Get(TodayPlanKey);
    public static string TodayDetails => Get(TodayDetailsKey);
    public static string TodayTimeShape => Get(TodayTimeShapeKey);
    public static string TodayPriority => Get(TodayPriorityKey);
    public static string TodayRangeNeedsResult => Get(TodayRangeNeedsResultKey);
    public static string TodayNeedsReviewLabel => Get(TodayNeedsReviewLabelKey);

    public static string AnimePageDescription => Get(AnimePageDescriptionKey);
    public static string AnimeMockBadge => Get(AnimeMockBadgeKey);
    public static string AnimeSearchToolTip => Get(AnimeSearchToolTipKey);
    public static string AnimeSearchAutomationName => Get(AnimeSearchAutomationNameKey);
    public static string AnimeClearSearch => Get(AnimeClearSearchKey);
    public static string AnimeNextAiring => Get(AnimeNextAiringKey);
    public static string AnimeViewDetails => Get(AnimeViewDetailsKey);
    public static string AnimeCountdown => Get(AnimeCountdownKey);
    public static string AnimeStaticDemoTime => Get(AnimeStaticDemoTimeKey);
    public static string AnimeThisSeason => Get(AnimeThisSeasonKey);
    public static string AnimeSeasonSummary => Get(AnimeSeasonSummaryKey);
    public static string AnimeOpenSeason => Get(AnimeOpenSeasonKey);
    public static string AnimeSelectedAnime => Get(AnimeSelectedAnimeKey);
    public static string AnimeMockStatus => Get(AnimeMockStatusKey);
    public static string AnimeReloadMock => Get(AnimeReloadMockKey);

    public static string WidgetWindowTitle => Get(WidgetWindowTitleKey);
    public static string WidgetSubtitle => Get(WidgetSubtitleKey);
    public static string WidgetHeaderRegion => Get(WidgetHeaderRegionKey);
    public static string WidgetStateToolTip => Get(WidgetStateToolTipKey);
    public static string WidgetClose => Get(WidgetCloseKey);
    public static string WidgetExpandedLayout => Get(WidgetExpandedLayoutKey);
    public static string WidgetTodayTab => Get(WidgetTodayTabKey);
    public static string WidgetAnimeTab => Get(WidgetAnimeTabKey);
    public static string WidgetPrimaryNextUp => Get(WidgetPrimaryNextUpKey);
    public static string WidgetNow => Get(WidgetNowKey);
    public static string WidgetUpcoming => Get(WidgetUpcomingKey);
    public static string WidgetSummary => Get(WidgetSummaryKey);
    public static string WidgetTodaySummaryFull => Get(WidgetTodaySummaryFullKey);
    public static string WidgetTodaySummaryCompact => Get(WidgetTodaySummaryCompactKey);
    public static string WidgetComplete => Get(WidgetCompleteKey);
    public static string WidgetSnooze => Get(WidgetSnoozeKey);
    public static string WidgetReschedule => Get(WidgetRescheduleKey);
    public static string WidgetPrimaryNextAiring => Get(WidgetPrimaryNextAiringKey);
    public static string WidgetTonight => Get(WidgetTonightKey);
    public static string WidgetWatched => Get(WidgetWatchedKey);
    public static string WidgetWatchLater => Get(WidgetWatchLaterKey);
    public static string WidgetScheduleTask => Get(WidgetScheduleTaskKey);
    public static string WidgetFooterLocalMock => Get(WidgetFooterLocalMockKey);
    public static string WidgetQuickAdd => Get(WidgetQuickAddKey);
    public static string WidgetReminders => Get(WidgetRemindersKey);
    public static string WidgetSimulateReminder => Get(WidgetSimulateReminderKey);
    public static string WidgetHighPriority => Get(WidgetHighPriorityKey);
    public static string WidgetAlertTitle => Get(WidgetAlertTitleKey);
    public static string WidgetAlertBody => Get(WidgetAlertBodyKey);
    public static string WidgetCurrentPage => Get(WidgetCurrentPageKey);
    public static string WidgetOpenReminderDrawer => Get(WidgetOpenReminderDrawerKey);
    public static string WidgetDismissAlert => Get(WidgetDismissAlertKey);
    public static string WidgetQuickAddHeading => Get(WidgetQuickAddHeadingKey);
    public static string WidgetQuickAddDescription => Get(WidgetQuickAddDescriptionKey);
    public static string WidgetQuickAddToolTip => Get(WidgetQuickAddToolTipKey);
    public static string WidgetAdd => Get(WidgetAddKey);
    public static string WidgetReminderDrawerHeading => Get(WidgetReminderDrawerHeadingKey);
    public static string WidgetReminderDrawerTitle => Get(WidgetReminderDrawerTitleKey);
    public static string WidgetTaskReminderMeta => Get(WidgetTaskReminderMetaKey);
    public static string WidgetUnread => Get(WidgetUnreadKey);
    public static string WidgetAnimeReminderTitle => Get(WidgetAnimeReminderTitleKey);
    public static string WidgetAnimeReminderMeta => Get(WidgetAnimeReminderMetaKey);
    public static string WidgetPending => Get(WidgetPendingKey);
    public static string WidgetMarkReminderRead => Get(WidgetMarkReminderReadKey);

    public static string Get(string key)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);
        return ResourceManager.GetString(key, CultureInfo.CurrentUICulture)
            ?? string.Format(CultureInfo.InvariantCulture, MissingResourceCompositeFormat, key);
    }

#pragma warning disable CA1863 // CompositeFormat instances are cached per stable resource key above.
    public static string Format(string key, params object[] arguments)
    {
        var compositeFormat = CompositeFormats.GetOrAdd(
            key,
            static resourceKey => CompositeFormat.Parse(Get(resourceKey)));
        return string.Format(CultureInfo.CurrentCulture, compositeFormat, arguments);
    }
#pragma warning restore CA1863
}
