<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ReminNote.Core</RootNamespace>
    <AssemblyName>ReminNote.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" />
  </ItemGroup>
</Project>
